# The GitHub user that owns the repos you want to examine
github_user:
 - <github-username>

# List all the repos to grab data from
github_repos:
 - <repo-name>

# Thee package managers this code supports
package_manager_urls:
 - https://www.nuget.org/packages/<path-to-your-package>
 - https://www.npmjs.com/package/<path-to-your-package>
 - https://packagist.org/packages/<path-to-your-package>
 - https://pypi.python.org/pypi/<path-to-your-package>
 - https://rubygems.org/gems/<path-to-your-package>

# This email will be sent upon successful execution
email:
  from: 'First Last <email@example.com>'
  to: 'First Last <email@example.com>'
  subject: 'Your Subject'
  body: 'The Email Body in HTML.'
